# Generated by Django 5.1.1 on 2026-05-08 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_term', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_results', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('rating', models.CharField(blank=True, default='', max_length=20)),
                ('reviews_count', models.IntegerField(default=0)),
                ('rating_reviews', models.CharField(blank=True, default='', max_length=50)),
                ('category', models.CharField(blank=True, default='', max_length=200)),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('website', models.URLField(blank=True, default='', max_length=500)),
                ('unique_key', models.CharField(db_index=True, max_length=600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='scraper.scrapejob')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('job', 'unique_key')},
            },
        ),
    ]
