# Generated by Django 5.1.1 on 2026-05-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='place',
            name='enriched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='facebook',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='place',
            name='instagram',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='place',
            name='lead_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='lead_status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('interested', 'Interested'), ('converted', 'Converted'), ('rejected', 'Rejected')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='place',
            name='linkedin',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='place',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='place',
            name='source',
            field=models.CharField(default='google_maps', max_length=30),
        ),
        migrations.AddField(
            model_name='place',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='scrapejob',
            name='source',
            field=models.CharField(choices=[('google_maps', 'Google Maps'), ('justdial', 'JustDial')], default='google_maps', max_length=30),
        ),
    ]
