# Generated by Django 5.1.1 on 2026-05-08 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_place_email_place_enriched_place_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Friendly name e.g. 'Sales Inbox'", max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sender_name', models.CharField(blank=True, default='', help_text='Display name shown to recipients', max_length=100)),
                ('app_password', models.CharField(help_text='16-char Gmail App Password', max_length=64)),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=100)),
                ('smtp_port', models.IntegerField(default=587)),
                ('use_tls', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('daily_limit', models.IntegerField(default=400, help_text='Gmail allows ~500/day')),
                ('sent_today', models.IntegerField(default=0)),
                ('last_reset', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_default', 'email'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('body_html', models.TextField(help_text='HTML body. Use {{name}}, {{category}} etc.')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('times_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='scrapejob',
            name='source',
            field=models.CharField(choices=[('google_maps', 'Google Maps'), ('justdial', 'JustDial'), ('indiamart', 'IndiaMART')], default='google_maps', max_length=30),
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254)),
                ('to_name', models.CharField(blank=True, default='', max_length=200)),
                ('subject', models.CharField(max_length=300)),
                ('body_html', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraper.emailaccount')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='scraper.place')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraper.emailtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
