# Generated by Django 5.1.1 on 2026-05-08 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_emailaccount_emailtemplate_alter_scrapejob_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeminiSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, default='', max_length=200)),
                ('model', models.CharField(default='gemini-2.0-flash-exp', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='place',
            name='enriched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='enrichment_log',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='place',
            name='enrichment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='place',
            name='last_change_log',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='place',
            name='times_seen',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='place',
            name='unique_key',
            field=models.CharField(db_index=True, max_length=600, unique=True),
        ),
        migrations.CreateModel(
            name='AIGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('email_write', 'Email Writer'), ('reply', 'Reply Assist'), ('improve', 'Improve Text'), ('subject', 'Subject Suggest')], max_length=30)),
                ('prompt', models.TextField(blank=True, default='')),
                ('output', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scraper.place')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
