# Generated by Django 5.1.1 on 2026-05-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_geminisetting_alter_place_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigenerationlog',
            name='model',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='aigenerationlog',
            name='output_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aigenerationlog',
            name='prompt_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aigenerationlog',
            name='total_tokens',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aigenerationlog',
            name='kind',
            field=models.CharField(choices=[('email_write', 'Email Writer'), ('reply', 'Reply Assist'), ('improve', 'Improve Text'), ('subject', 'Subject Suggest'), ('test', 'Test')], max_length=30),
        ),
    ]
