# Generated by Django 5.1.1 on 2026-05-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_aigenerationlog_model_aigenerationlog_output_tokens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='claimed',
            field=models.BooleanField(default=False, help_text='Owner-verified business'),
        ),
        migrations.AddField(
            model_name='place',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='place',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='Any other extracted fields'),
        ),
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='opening_hours',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='place',
            name='photos_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='place_url',
            field=models.URLField(blank=True, default='', help_text='Direct Google Maps link', max_length=500),
        ),
        migrations.AddField(
            model_name='place',
            name='plus_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='place',
            name='price_level',
            field=models.CharField(blank=True, default='', help_text='₹/₹₹/₹₹₹/₹₹₹₹', max_length=10),
        ),
        migrations.AddField(
            model_name='place',
            name='secondary_categories',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='place',
            name='services',
            field=models.TextField(blank=True, default='', help_text='Comma-separated: Dine-in, Takeout, Delivery, etc.'),
        ),
    ]
