# Generated by Django 5.1.1 on 2026-05-23 11:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_incentiverule_breaklog_leadimportjob_callergoal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Morning Shift', max_length=100)),
                ('start_time', models.TimeField(help_text='Local time, e.g. 09:00')),
                ('end_time', models.TimeField(help_text='Local time, e.g. 17:00')),
                ('days', models.CharField(default='mon,tue,wed,thu,fri', help_text='Comma-separated codes from: mon,tue,wed,thu,fri,sat,sun', max_length=64)),
                ('timezone_name', models.CharField(default='Asia/Kolkata', max_length=64)),
                ('color', models.CharField(default='#6366f1', help_text='Hex color for calendar display', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.AddField(
            model_name='callerprofile',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Reporting manager — leave empty for top-level', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='callerprofile',
            name='timezone',
            field=models.CharField(blank=True, default='Asia/Kolkata', help_text='IANA timezone, e.g. Asia/Kolkata', max_length=64),
        ),
        migrations.AlterField(
            model_name='callerprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('caller', 'Caller')], default='caller', max_length=20),
        ),
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('entity', models.CharField(choices=[('calls', 'Call Logs'), ('assignments', 'Lead Assignments'), ('leads', 'Leads'), ('attendance', 'Attendance')], default='calls', max_length=30)),
                ('config', models.JSONField(blank=True, default=dict, help_text='{dimensions:[], metrics:[], filters:{}, chart:"bar"}')),
                ('is_shared', models.BooleanField(default=False, help_text='Visible to other admins')),
                ('times_run', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
                ('effective_to', models.DateField(blank=True, help_text='Leave empty for ongoing assignment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='scraper.shift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
    ]
