# Generated by Django 5.1.1 on 2026-05-23 11:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_shift_callerprofile_manager_callerprofile_timezone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='clicked_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='clicks',
            field=models.JSONField(blank=True, default=list, help_text='List of {url, at} per click'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='last_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='open_token',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Unique token for tracking pixel + clicks', max_length=64),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='opened_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.CreateModel(
            name='AvailabilitySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Public URL slug e.g. /meet/bhavesh/', max_length=80, unique=True)),
                ('title', models.CharField(default='Book a meeting', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('slot_duration_min', models.IntegerField(default=30)),
                ('buffer_min', models.IntegerField(default=10, help_text='Buffer time between meetings')),
                ('advance_days', models.IntegerField(default=14, help_text='How many days ahead to allow booking')),
                ('min_notice_hours', models.IntegerField(default=4, help_text='Min hours notice required')),
                ('working_hours', models.JSONField(blank=True, default=dict)),
                ('color', models.CharField(default='#6366f1', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('require_phone', models.BooleanField(default=True)),
                ('timezone_name', models.CharField(default='Asia/Kolkata', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('stop_on_reply', models.BooleanField(default=True, help_text='Stop if lead replies (manual mark for now)')),
                ('stop_on_status', models.CharField(blank=True, default='converted,rejected', help_text='Comma-sep lead_status values that stop the sequence', max_length=100)),
                ('times_used', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booker_name', models.CharField(max_length=200)),
                ('booker_email', models.EmailField(max_length=254)),
                ('booker_phone', models.CharField(blank=True, default='', max_length=30)),
                ('scheduled_at', models.DateTimeField()),
                ('duration_min', models.IntegerField(default=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No Show')], default='confirmed', max_length=20)),
                ('cancel_token', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to='scraper.place')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='scraper.availabilityschedule')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='SequenceEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step_order', models.IntegerField(default=0, help_text='0 = not yet sent, 1 = step 1 sent, etc.')),
                ('next_send_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('stopped', 'Stopped')], default='active', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('stop_reason', models.CharField(blank=True, default='', max_length=200)),
                ('enrolled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='scraper.place')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='scraper.emailsequence')),
            ],
            options={
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.AddField(
            model_name='emaillog',
            name='sequence_enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='scraper.sequenceenrollment'),
        ),
        migrations.CreateModel(
            name='SequenceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('days_after_previous', models.IntegerField(default=3, help_text='Days to wait after previous step (0=immediate)')),
                ('subject_override', models.CharField(blank=True, default='', help_text='Optional override for the template subject', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='scraper.emailsequence')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scraper.emailtemplate')),
            ],
            options={
                'ordering': ['sequence', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='sequenceenrollment',
            index=models.Index(fields=['status', 'next_send_at'], name='scraper_seq_status_4df19e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sequenceenrollment',
            unique_together={('sequence', 'place')},
        ),
        migrations.AlterUniqueTogether(
            name='sequencestep',
            unique_together={('sequence', 'order')},
        ),
    ]
