# Generated by Django 5.1.1 on 2026-05-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0010_emaillog_clicked_count_emaillog_clicks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='callerprofile',
            name='auto_assign_enabled',
            field=models.BooleanField(default=False, help_text='If ON: system auto-assigns leads up to daily_quota. If OFF: admin assigns manually only.'),
        ),
        migrations.AlterField(
            model_name='callerprofile',
            name='daily_quota',
            field=models.IntegerField(default=100, help_text='Suggested daily target (for goals/progress only)'),
        ),
    ]
