# Generated by Django 5.1.1 on 2026-09-28 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0011_callerprofile_auto_assign_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('reason', models.CharField(choices=[('unsubscribed', 'Unsubscribed'), ('bounced', 'Hard bounce'), ('complained', 'Marked as spam'), ('manual', 'Added by hand')], default='unsubscribed', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='emaillog',
            name='bounce_reason',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='bounced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='bounced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='unsubscribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['place', 'status'], name='scraper_ema_place_i_83b89d_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['status', 'sent_at'], name='scraper_ema_status_1fb83d_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['to_email'], name='scraper_ema_to_emai_a675c1_idx'),
        ),
        migrations.AddField(
            model_name='suppression',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppressions', to='scraper.place'),
        ),
    ]
