# Generated by Django 5.1.1 on 2026-09-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0012_suppression_emaillog_bounce_reason_emaillog_bounced_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['lead_status'], name='scraper_pla_lead_st_7b5aa8_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['-lead_score'], name='scraper_pla_lead_sc_7ab5b8_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['category'], name='scraper_pla_categor_287ef0_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['email'], name='scraper_pla_email_755023_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['source', 'lead_status'], name='scraper_pla_source_09f9c2_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['-created_at'], name='scraper_pla_created_1a2c83_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['enrichment_status'], name='scraper_pla_enrichm_7faf9c_idx'),
        ),
    ]
