# Generated by Django 5.1.1 on 2026-09-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0013_place_scraper_pla_lead_st_7b5aa8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='follow_up_note',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='place',
            name='next_follow_up',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
