# Generated by Django 5.1.1 on 2026-09-28 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0014_place_follow_up_note_place_next_follow_up'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialTouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('action', models.CharField(choices=[('visited', 'Profile opened'), ('followed', 'Followed / liked'), ('connected', 'Connection request sent'), ('messaged', 'Message sent'), ('replied', 'They replied'), ('no_response', 'No response')], default='visited', max_length=20)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_touches', to='scraper.place')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_touches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['place', 'platform'], name='scraper_soc_place_i_29e33a_idx'), models.Index(fields=['action', 'created_at'], name='scraper_soc_action_68d921_idx')],
            },
        ),
    ]
