# Generated by Django 5.1.1 on 2026-09-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0015_socialtouch'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('platform', models.CharField(blank=True, default='', help_text='Leave blank to use on any network', max_length=20)),
                ('body', models.TextField(help_text='Supports {{name}}, {{category}}, {{city}}, {{website}}')),
                ('times_used', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
